version: '3.9'

services:
  eth_spike:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./app:/home/jovyan/app
    command: tail -F anything